# Generated by Django 4.2 on 2025-03-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_news_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=32),
        ),
    ]
