# Generated by Django 4.2 on 2025-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_news_options_alter_news_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/"),
        ),
    ]
