# Generated by Django 4.2 on 2025-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
